version: '3.4'
services:
  confluence:
    image: leloimr/confluence:8.7.1
    container_name: confluence-srv
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - TZ=Asia/Ho_Chi_Minh
    #      - JVM_MINIMUM_MEMORY=1g
    #      - JVM_MAXIMUM_MEMORY=12g
    #      - JVM_CODE_CACHE_ARGS='-XX:InitialCodeCacheSize=1g -XX:ReservedCodeCacheSize=8g'
    depends_on:
      - mysql
    ports:
      - "8095:8090"
    volumes:
      - home_data:/var/confluence
    restart: always
    networks:
      - network-bridge

  mysql:
    image: mysql:8.0
    container_name: mysql-confluence
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - MYSQL_DATABASE=confluence
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=confluence
      - MYSQL_PASSWORD=123123
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_bin', '--transaction-isolation=READ-COMMITTED', '--innodb_log_file_size=256M', '--max_allowed_packet=256M','--log_bin_trust_function_creators=1']
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    networks:
      - network-bridge

 # postgres:
 #     image: postgres:latest
 #     container_name: bamboo-postgressql
 #     environment:
 #       PGDATA: /var/lib/postgresql/data/pgdata
 #       POSTGRES_DB: bamboo
 #       POSTGRES_USER: bamboo
 #       POSTGRES_PASSWORD: 123123
 #     volumes:
 #       - postgres_data:/var/lib/postgresql/data/pgdata
 #     restart: always
 #     networks:
 #       - network-bridge

networks:
  network-bridge:
    driver: bridge

volumes:
  home_data:
    external: false
  mysql_data:
    external: false
  # postgres_data:
  # external: false
